[cursor]
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 9.0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"
